version: '3'
services:
  reverseproxy:
    image: mkhill/reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
      - backend-filter
  backend-user:
    image: mkhill/udagram-user
    environment:
      UDAGRAM_DB_USERNAME: $UDAGRAM_DB_USERNAME
      UDAGRAM_DB_PASSWORD: $UDAGRAM_DB_PASSWORD
      UDAGRAM_DB_DATABASE: $UDAGRAM_DB_DATABASE
      UDAGRAM_DB_HOST: $UDAGRAM_DB_HOST
      UDAGRAM_DB_DIALECT: $UDAGRAM_DB_DIALECT
      UDAGRAM_AWS_REGION: $UDAGRAM_AWS_REGION
      UDAGRAM_AWS_PROFILE: $UDAGRAM_AWS_PROFILE
      UDAGRAM_AWS_MEDIA_BUCKET: $UDAGRAM_AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: 'http://localhost:8100'
  backend-feed:
    image: mkhill/udagram-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      UDAGRAM_DB_USERNAME: $UDAGRAM_DB_USERNAME
      UDAGRAM_DB_PASSWORD: $UDAGRAM_DB_PASSWORD
      UDAGRAM_DB_DATABASE: $UDAGRAM_DB_DATABASE
      UDAGRAM_DB_HOST: $UDAGRAM_DB_HOST
      UDAGRAM_DB_DIALECT: $UDAGRAM_DB_DIALECT
      UDAGRAM_AWS_REGION: $UDAGRAM_AWS_REGION
      UDAGRAM_AWS_PROFILE: $UDAGRAM_AWS_PROFILE
      UDAGRAM_AWS_MEDIA_BUCKET: $UDAGRAM_AWS_MEDIA_BUCKET
      UDAGRAM_IMAGE_FILTER_URL: $UDAGRAM_IMAGE_FILTER_URL
      JWT_SECRET: $JWT_SECRET
      URL: 'http://localhost:8100'
  backend-filter:
    image: mkhill/udagram-filter
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      UDAGRAM_DB_USERNAME: $UDAGRAM_DB_USERNAME
      UDAGRAM_DB_PASSWORD: $UDAGRAM_DB_PASSWORD
      UDAGRAM_DB_DATABASE: $UDAGRAM_DB_DATABASE
      UDAGRAM_DB_HOST: $UDAGRAM_DB_HOST
      UDAGRAM_DB_DIALECT: $UDAGRAM_DB_DIALECT
      UDAGRAM_AWS_REGION: $UDAGRAM_AWS_REGION
      UDAGRAM_AWS_PROFILE: $UDAGRAM_AWS_PROFILE
      UDAGRAM_AWS_MEDIA_BUCKET: $UDAGRAM_AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: 'http://localhost:8100'
  frontend:
    image: mkhill/udagram-frontend:local
    ports:
      - '8100:80'
