apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-filter
  name: backend-filter
spec:
  ports:
    - name: '8080'
      port: 8080
      targetPort: 8080
  selector:
    service: backend-filter
